//Day01
//InClass Questions
//Problem1
//Write a program that takes an integer as input and prints whether it is even or odd.

//Problem2
//Problem: Temperature Check
//Create a script that takes the temperature in Celsius as input and outputs a message based on the temperature range (e.g., "It's cold," "It's warm," or "It's hot").

//Problem3.
//Write a JavaScript program that takes a temperature in Celsius as input and converts it to Fahrenheit. 
//The formula to convert Celsius to Fahrenheit is:
//Fahrenheit=(Celsius * 9/5)+32;



//Day01
//Take Home

//1.Multiples of 3 or 5
//2.Grading
//3.Leap Year




//Project Euler Problems


1.//If we list all the natural numbers below 10 that are multiples of 3 or 5 , we get 3,5,6 and 9.The sum of these multiples is 23.
//Find the sum of all the multiples of 3 or 5 below 1000.
// Euler Problem1.

function listOfMultiples(num){
    let sum = 0;
    for(let i=1;i<num;i++){
        if(i%3==0 || i%5 ==0){
            sum+=i;

        }

    }

    return sum

}

console.log("List Of Multiples " +listOfMultiples(1000));


2.//Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with and , the first terms will be
// 1,2,3,5,8,13,21,34,55,89,...
// By considering the terms in the Fibonacci sequence whose values do not exceed four million,find the sum if the even-valued terms.

function FibonacciSequence(){
  let result = [1,2]
  for(let i =1;i<4000000;i++){
    result.push(result[i]+result[i-1])

  }

  return result







}
console.log(FibonacciSequence())

function sumOfEvenValuedTerms(){
    let array = FibonacciSequence()
    let sumofEven = 0
    for (let i = 0 ;i<array.length;i++){
       if( i % 2 == 0){
        sumofEven+=array[i]
          
       }

    }
    return sumofEven

}

console.log("Sum of Even Valued Sum "+sumOfEvenValuedTerms());



3.


